Auto sidebar
one-among-us/about-site pull request #18
Opened 2024-11-18 15:13 UTC by BeiyanYunyi

2024-11-18 22:33 UTC, sauricat requested changes
感觉不错。除了一个地方可能要看下，就是 footer 都显示不出来了？

2024-11-18 22:33 UTC, sauricat commented on content/.vitepress/config.ts
>          footer: {
感觉不错。除了一个地方可能要看下，就是 footer 都显示不出来了？

2024-11-19 03:37 UTC, BeiyanYunyi commented
According to [the document](https://vitepress.dev/reference/default-theme-footer#footer), footer will be disabled when sidebar is displayed.

2024-11-19 04:07 UTC, BeiyanYunyi commented
Since d85d793, all home pages have footer now. The main reason is they was using global component before, instead of `home` layout.

2024-11-19 15:29 UTC, sauricat approved these changes

2024-11-19 15:29 UTC, merged